In [ ]:
# Домашнее задание «Библиотека numpy. Вычислительные задачи»


In [ ]:
# ЗАДАНИЕ 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
np.arange(10, 0, -1) # от 10 до 0 с шагом -1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# ЗАДАНИЕ 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
np.random.seed()
a = np.random.randint(10, size=(8, 8))
a

array([[1, 2, 2, 6, 3, 4, 1, 7],
       [6, 4, 9, 7, 6, 3, 4, 9],
       [2, 4, 6, 7, 6, 4, 5, 0],
       [9, 0, 2, 9, 3, 0, 6, 7],
       [0, 2, 5, 6, 0, 1, 4, 7],
       [8, 1, 7, 1, 2, 1, 1, 5],
       [8, 1, 9, 9, 8, 1, 8, 5],
       [7, 3, 4, 0, 2, 6, 3, 4]])

In [5]:
diag = np.diagonal(a)
diag

array([1, 4, 6, 9, 0, 1, 8, 4])

In [6]:
diag.sum()

33

In [ ]:
# ЗАДАНИЕ 3
#Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [ ]:
# не знаю, верным ли путем пошла, но в документации нашла, что для решения данной системы матричным методом, 
# нужно запистаь ее в таком виде, чтобы каждое уравнение содержало 3 переменных 

In [12]:
M2 = np.array([[4, 2, 1], [1, 3, 0], [5, 4, 0]]) # Матрица (левая часть системы)

In [13]:
v2 = np.array( [4, 12, -3]) # Вектор (правая часть системы)

In [4]:
from numpy import linalg

In [11]:
linalg.solve(M2, v2)

array([-5.18181818,  5.72727273, 13.27272727])

In [ ]:
# “ЗАДАНИЕ 4 ”
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [20]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


In [21]:
next_user = np.array([0, 1, 2, 0, 0, 0])

In [22]:
# считаем длину вектора нового клиента
next_user_length = np.sqrt( (next_user**2).sum() )

In [23]:
# создаем новый список 
new_list = []

In [46]:
for num, user in enumerate(users_stats):
    user_length = np.sqrt( (user**2).sum() ) # считаем длину для каждого юзера в users_stats
    # print(user_length)
    scalar = np.dot(user, next_user) # считаем скалярное произведение 
    # print(scalar)
    cosine  = scalar / (next_user_length * user_length)# считаем косинус угла между ними 
    #print(num,cosine)
    new_list.append(cosine)
    
print(max(new_list))
print(new_list.index(0.9486832980505138, 0, 9)) # выводим макс значение из списка и индекс этого числа - т.е получаем номер юзера

0.9486832980505138
7
